server:
  port: 8888

spring:
  application:
    name: gateway
  cloud:
    consul:
      host: consul
      port: 8500

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://tempo:4318/v1/traces